name: macOS
description: Build for macOS

inputs:
  GITHUB_TOKEN:
    required: true
    description: On macos runners we often hit API limits. Using this token avoid this.

runs:
  using: "composite"
  steps:
    - uses: extractions/setup-just@v1
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    - name: Install toolchain
      shell: bash
      run: just default-toolchain
    - uses: Swatinem/rust-cache@v1
    - name: Build
      shell: bash
      run: just xcodebuild-xcframework
    - name: Check x86_64 darwin
      shell: bash
      run: just check apple x86_64-apple-darwin
    - name: Check aarch64 darwin
      shell: bash
      # TODO: Additional clippy checks for different targets (iOS)
      run: just check apple aarch64-apple-darwin
    - name: Test
      shell: bash
      # TODO: Additional test runs for different targets
      run: just test apple aarch64-apple-darwin
    - name: Build Example
      shell: bash
      run: cd apple/xcode && xcodebuild -scheme "example (iOS)" -arch arm64 -sdk iphoneos build CODE_SIGNING_ALLOWED=NO
    - name: Build Swift Package (arm64)
      shell: bash
      run: cd apple/MapLibreRs && swift build --arch=arm64
    - name: Build Swift Package (x86_64)
      shell: bash
      run: cd apple/MapLibreRs && swift build --arch=x86_64

