name: setup
description: Setup


inputs:
  nightly:
    required: false
    description: If true stable will be installed, if false nightly
  targets:
    required: false
    description: space separated list of rustc targets

runs:
  using: "composite"
  steps:
    - name: Install just
      uses: ./.github/actions/cargo-install
      with:
        name: just
    - name: Install stable toolchain
      if: ${{ !inputs.nightly }}
      shell: bash
      run: just stable-toolchain
    - name: Install nightly toolchain
      if: ${{ inputs.nightly }}
      shell: bash
      run: just nightly-toolchain
    - name: Install targets
      if: ${{ inputs.targets }}
      shell: bash
      run: just stable-targets ${{ inputs.targets }}
    - uses: Swatinem/rust-cache@v2
    - name: Install just
      uses: ./.github/actions/cargo-install
      with:
        name: just
