name: docs
description: Build documentation

runs:
  using: "composite"
  steps:
    - uses: extractions/setup-just@v1
    - name: Install toolchain
      shell: bash
      run: just default-toolchain
    - uses: Swatinem/rust-cache@v1
    - name: Install mdbook
      shell: bash
      run: cargo install mdbook --no-default-features --vers "^0.4.0"
    - name: Install Dependencies
      shell: bash
      run: sudo apt-get install -y libwayland-dev libxkbcommon-dev # Required for winit
    - name: Build
      working-directory: docs
      shell: bash
      run: mdbook build
    - name: API Documentation
      shell: bash
      run: cargo doc -p maplibre --no-deps --lib --all-features --document-private-items
