name: setup-binstall
description: Setup binstall

runs:
  using: "composite"
  steps:
    - name: Setup default toolchain
      shell: bash
      run: rustup show # Installs toolchain specified in rust-toolchain.toml
    - name: Install binstall
      shell: bash
      run: |
        # Install with debug profile -> faster compilation
        cargo install --debug cargo-binstall
