name: linux-demo
description: Build linux-demo for linux

runs:
  using: "composite"
  steps:
    - uses: extractions/setup-just@v1
    - name: Install toolchain
      shell: bash
      run: just default-toolchain
    - uses: Swatinem/rust-cache@v1
    - name: Install Dependencies
      shell: bash
      run: sudo apt-get install -y libwayland-dev libxkbcommon-dev # Required for winit
    - name: Build
      shell: bash
      run: cargo build -p maplibre-demo
    - name: Check
      shell: bash
      run: just check maplibre-demo x86_64-unknown-linux-gnu
    - uses: actions/upload-artifact@v2
      with:
        name: maplibre-rs
        path: target/x86_64-unknown-linux-gnu/debug/maplibre-demo