name: webgpu
description: Build for webgpu

runs:
  using: "composite"
  steps:
    - uses: extractions/setup-just@v1
    - name: Install nightly toolchain
      shell: bash
      run: just nightly-toolchain
    - uses: Swatinem/rust-cache@v1
    - name: Build lib
      shell: bash
      run: just web-lib esbuild
    - name: Build demo
      shell: bash
      run: just web-demo build
    - name: Check
      shell: bash
      run: just check web wasm32-unknown-unknown
    - name: Check
      shell: bash
      run: just test web wasm32-unknown-unknown
