name: webgpu
description: Build for webgpu

runs:
  using: "composite"
  steps:
    - uses: extractions/setup-just@v1
    - name: Install nightly toolchain
      shell: bash
      run: just nightly-toolchain
    - uses: Swatinem/rust-cache@v1
    - name: Build
      shell: bash
      run: just webpack-production
