name: android
description: Build for android

runs:
  using: "composite"
  steps:
    - uses: extractions/setup-just@v1
    - name: Install nightly toolchain
      shell: bash
      run: just nightly-toolchain-android
    - uses: Swatinem/rust-cache@v1
    - name: Build
      shell: bash
      run: just build-android
#    - name: Check x86_64
#      shell: bash
#      run: just check maplibre-android x86_64-linux-android
#    - name: Check aarch64
#      shell: bash
#      run: just check maplibre-android aarch64-linux-android
