name: android
description: Build for android

runs:
  using: "composite"
  steps:
    - uses: extractions/setup-just@v1
    - name: Install nightly toolchain
      shell: bash
      run: just nightly-toolchain-android
    - uses: Swatinem/rust-cache@v1
    - name: Build
      shell: bash
      run: just build-android
      # TODO: Additional clippy checks for different targets
    - name: Check x86_64
      shell: bash
      run: |
        env "AR_x86_64-linux-android=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" \
        env "CC_x86_64-linux-android=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android30-clang" \
        just check maplibre-android x86_64-linux-android
    - name: Check aarch64
      shell: bash
      run: |
        env "AR_aarch64-linux-android=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" \
        env "CC_aarch64-linux-android=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang" \
        just check maplibre-android aarch64-linux-android
    # FIXME: Requires cross-compilation
    #- name: Test
    #  shell: bash
    #  # TODO: Additional test runs for different targets
    #  run: just test maplibre-android aarch64-linux-android