name: cargo-install
description: Install a dependency from cargo

inputs:
  name:
    required: true
    description: Name of the dependency

runs:
  using: "composite"
  steps:
    - name: Install ${{ inputs.name }}
      shell: bash
      run: cargo binstall --no-confirm --force ${{ inputs.name }}
