#!/bin/bash
set -e

webgl_flag=""

TEMP=$(getopt --long -o "g" "$@")
eval set -- "$TEMP"
while true; do
  case "$1" in
  -g)
    webgl_flag="--features web-webgl"
    shift 2
    ;;
  *)
    break
    ;;
  esac
done

# shellcheck disable=SC2086
RUSTFLAGS=--cfg=web_sys_unstable_apis cargo build $webgl_flag --target wasm32-unknown-unknown --bin mapr
wasm-bindgen --target web --out-dir web target/wasm32-unknown-unknown/debug/mapr.wasm

xdg-open "https://localhost:5555/web/mapr.html"
python3 tools/tls-http-server.py
