name: download-test-data
description: Download test data

runs:
  using: "composite"
  steps:
    - name: Download
      shell: bash
      run: wget -O test-data/munich-15.mbtiles https://data.maxammann.org/munich-15.mbtiles
