name: benchmarks
description: Run benchmarks

runs:
  using: "composite"
  steps:
    - uses: extractions/setup-just@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Install toolchain
      shell: bash
      run: just default-toolchain
    - uses: Swatinem/rust-cache@v1
    - name: Install Dependencies
      shell: bash
      run: sudo apt-get install -y libwayland-dev libxkbcommon-dev # Required for winit
    - name: Check
      shell: bash
      run: just check benchmarks x86_64-unknown-linux-gnu
