name: install-driver
description: Install drivers

runs:
  using: "composite"
  steps:
    - name: Install Mesa Dependencies
      shell: bash
      run: |
        sudo apt-get update -y -qq
        
        # llvmpipe/lavapipe
        sudo add-apt-repository ppa:oibaf/graphics-drivers -y
        # vulkan sdk
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-focal.list https://packages.lunarg.com/vulkan/lunarg-vulkan-focal.list
        sudo apt-get update
        sudo apt install -y libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers vulkan-sdk
    - name: wgpu info
      shell: bash
      run: |
        cargo install --git "https://github.com/gfx-rs/wgpu" wgpu-info
        wgpu-info
