name: install-driver
description: Install drivers

runs:
  using: "composite"
  steps:
    - name: Install Mesa Dependencies
      shell: bash
      run: |
        sudo apt-get update -y -qq
        
        # Get latest drivers. The lavapipe in Ubuntu 20.04 SEGVs.
        sudo add-apt-repository ppa:oibaf/graphics-drivers -y

        sudo apt install -y libegl1-mesa libgl1-mesa-dri libxcb-xfixes0-dev mesa-vulkan-drivers
    - name: wgpu info
      shell: bash
      run: |
        cargo install --git "https://github.com/gfx-rs/wgpu" wgpu-info
        wgpu-info
