name: install-system-dependencies
description: Install system dependencies

runs:
  using: "composite"
  steps:
    - name: Install System Dependencies (Windows)
      if: runner.os == 'Windows'
      shell: powershell
      run: pacman -S --noconfirm protobuf
    - name: Install System Dependencies (Ubuntu)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get install -y \
          protobuf-compiler \
          libwayland-dev libxkbcommon-dev # Required for winit
    - name: Install System Dependencies (Ubuntu)
      if: runner.os == 'macOS'
      shell: bash
      run: brew install protobuf

    - name: Check Depdenencies
      if: runner.os != 'Windows'
      shell: bash
      run: |
        protoc --version
    - name: Check Depdenencies
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        protoc --version
