name: Build demo for Linux

on:
  workflow_call:

jobs:
  demo-linux:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup binstall
        uses: ./.github/actions/setup-binstall
      - name: Install just
        uses: ./.github/actions/cargo-install
        with:
          name: just
      - name: Install toolchain
        shell: bash
        run: |
          just stable-toolchain
          just stable-targets x86_64-unknown-linux-gnu
      - uses: Swatinem/rust-cache@v2
      - name: Install Dependencies
        shell: bash
        run: sudo apt-get install -y libwayland-dev libxkbcommon-dev # Required for winit
      - name: Build
        shell: bash
        run: cargo build -p maplibre-demo --release --target x86_64-unknown-linux-gnu
      - name: Check
        shell: bash
        run: just check maplibre-demo x86_64-unknown-linux-gnu
      - name: Test x86_64 linux
        shell: bash
        run: just test maplibre-demo x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: maplibre-rs
          path: target/x86_64-unknown-linux-gnu/release/maplibre-demo
