name: Build demo for Linux

on:
  workflow_call:

jobs:
  demo-linux:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          targets: x86_64-unknown-linux-gnu
      - name: Install Dependencies
        uses: ./.github/actions/install-system-dependencies
      - name: Build
        shell: bash
        run: cargo build -p maplibre-demo --release --target x86_64-unknown-linux-gnu
      - name: Check
        shell: bash
        run: just check maplibre-demo x86_64-unknown-linux-gnu
      - name: Test x86_64 linux
        shell: bash
        run: just test maplibre-demo x86_64-unknown-linux-gnu
      - uses: actions/upload-artifact@v3
        with:
          name: maplibre-rs
          path: target/x86_64-unknown-linux-gnu/release/maplibre-demo
