name: Build android library

on:
  workflow_call:

jobs:
  library-android:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          nightly: true
          targets: x86_64-linux-android aarch64-linux-android i686-linux-android
      - name: Set NDK Version
        shell: bash
        run: |
          ANDROID_ROOT=/usr/local/lib/android
          ANDROID_SDK_ROOT=${ANDROID_ROOT}/sdk
          ANDROID_NDK_ROOT=${ANDROID_SDK_ROOT}/ndk-bundle
          ln -sfn $ANDROID_SDK_ROOT/ndk/23.2.8568313 $ANDROID_NDK_ROOT
      - name: Build
        shell: bash
        run: just build-android
        # TODO: Additional clippy checks for different targets
      - name: Check x86_64
        shell: bash
        run: |
          env "AR_x86_64-linux-android=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" \
          env "CC_x86_64-linux-android=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android30-clang" \
          just nightly-check maplibre-android x86_64-linux-android ""
      - name: Check aarch64
        shell: bash
        run: |
          env "AR_aarch64-linux-android=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" \
          env "CC_aarch64-linux-android=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang" \
          just nightly-check maplibre-android aarch64-linux-android ""
    # FIXME: Requires cross-compilation
    #- name: Test
    #  shell: bash
    #  # TODO: Additional test runs for different targets
    #  run: just test maplibre-android aarch64-linux-android
