name: Build android library

on:
  workflow_call:

jobs:
  library-android:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          nightly: true
          targets: x86_64-linux-android aarch64-linux-android i686-linux-android
      - name: Install Dependencies
        uses: ./.github/actions/install-system-dependencies
      - name: Build
        shell: bash
        run: just build-android
        # TODO: Additional clippy checks for different targets
      - name: Check x86_64
        shell: bash
        run: |
          env "AR_x86_64-linux-android=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" \
          env "CC_x86_64-linux-android=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android30-clang" \
          just nightly-check maplibre-android x86_64-linux-android ""
      - name: Check aarch64
        shell: bash
        run: |
          env "AR_aarch64-linux-android=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/llvm-ar" \
          env "CC_aarch64-linux-android=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android30-clang" \
          just nightly-check maplibre-android aarch64-linux-android ""
    # FIXME: Requires cross-compilation
    #- name: Test
    #  shell: bash
    #  # TODO: Additional test runs for different targets
    #  run: just test maplibre-android aarch64-linux-android
